@Restapi-net8_HostAddress = https://localhost:7198
@Restapi_net8_HostAddress = http://localhost:5299

GET {{Restapi_net8_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Restapi-net8_HostAddress}}/weatherforecast



###

GET {{Restapi_net8_HostAddress}}/api/superhero

###

POST {{Restapi-net8_HostAddress}}/api/categories
Content-Type: application/json

{
  //CreateCategoryRequestDTO
}

###
