version: '3.8'

services:
  restapi-net8:
    image: ${DOCKER_REGISTRY-}restapinet8
    build:
      context: .
      dockerfile: Restapi-net8/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection="Server=sqlserver;Database=YourDb;User Id=sa;Password=Phuc10122002;"
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Phuc101202
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ~/certificates:/https:ro
    depends_on:
      - sqlserver
      - redis
    command: >
      sh -c "until dotnet ef database update; do echo 'Đang chờ SQL Server...'; sleep 5; done && dotnet Restapi-net8.dll"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Phuc10122002
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:

  sqlserver-data:
    driver: local
  redis-data:
    driver: local
